---
title: Healing Hands
timezone: UTC
collections:
  missions:
    title: Missions
    output: true
    permalink: "/missions/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
owner: Healing Hands
first_published: 2018
email: info@healinghandsmission.com
address: P.O. Box 864, St. Charles, IL 60174
sass:
  style: compressed
markdown: kramdown
paginate: 10
paginate_path: "/news-and-events/page:num/"
_options:
  blog_image_path:
    width: 350
    height: 197
