# Welcome to Jekyll!
#

# Site settings
title: Healing Hands
owner: Healing Hands # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: info@healinghandsmission.com
address: P.O. Box 864, St. Charles, IL 60174
sass:
    style: compressed
markdown: kramdown

